In [1]:
import numpy as np
import pandas as pd
from fit_var import fit_var
from est_varma import estimate_varma
import matplotlib.pyplot as plt
import os
from est_model import estimate_model

In [2]:
# Load the data
data = np.loadtxt("output.csv", delimiter=',', skiprows=0)  # skiprows=0 to not skip the header
print(data)

[[ 3.  4.]
 [ 4.  3.]
 [12.  3.]
 [22.  3.]
 [10.  1.]
 [ 8.  1.]
 [ 8.  1.]
 [13.  0.]
 [ 6.  1.]
 [ 9.  0.]
 [14.  1.]
 [ 4.  0.]
 [ 2.  2.]
 [ 4.  4.]
 [18.  1.]
 [ 5.  1.]
 [10.  1.]
 [ 5.  2.]
 [ 4.  3.]
 [ 3.  1.]
 [12.  1.]
 [ 8.  1.]
 [ 5.  0.]
 [15.  2.]
 [ 7.  0.]
 [ 5.  2.]
 [ 3.  3.]
 [ 8.  1.]
 [ 4.  2.]
 [ 4.  1.]
 [ 8.  0.]
 [ 5.  3.]
 [ 1.  1.]
 [ 5.  0.]
 [ 8.  3.]
 [12.  3.]
 [12.  3.]
 [11.  3.]
 [20.  4.]
 [ 7.  5.]
 [ 8.  1.]
 [18.  3.]
 [ 2.  1.]
 [ 9.  2.]
 [15.  0.]
 [ 7.  0.]
 [ 2.  1.]
 [ 3.  0.]
 [10.  4.]
 [ 4.  7.]
 [12.  2.]
 [ 3.  0.]
 [ 9.  0.]
 [ 1.  0.]
 [14.  1.]
 [17.  2.]
 [15.  2.]
 [ 9.  1.]
 [16.  0.]
 [ 9.  1.]
 [ 5.  2.]
 [ 5.  2.]
 [ 6.  1.]
 [ 1.  0.]
 [13.  1.]
 [ 6.  3.]
 [ 6.  1.]
 [ 6.  2.]
 [ 5.  3.]
 [ 7.  0.]
 [ 4.  2.]
 [ 7.  2.]
 [ 7.  5.]
 [ 3.  0.]
 [ 2.  2.]
 [ 9.  0.]
 [ 7.  3.]
 [ 5.  0.]
 [10.  3.]
 [10.  2.]
 [ 4.  2.]
 [ 4.  0.]
 [ 1.  0.]
 [ 6.  0.]
 [ 6.  0.]
 [ 6.  0.]
 [12.  1.]
 [ 9.  0.]
 [ 1.  0.]
 [ 2.  1.]
 [ 7.  2.]

In [7]:
moyenne = data.mean(axis=0)
sd = data.std(axis=0)
print(moyenne)
print(sd)
print(sd**2)

[7.27671233 1.50410959]
[4.56941951 1.3681743 ]
[20.87959467  1.87190092]


In [3]:
# Center the data
def center_data(data):
    means = data.mean(axis=0)
    Y = data - means
    return Y

In [4]:
centered_data = center_data(data)
print(centered_data)

[[-4.27671233  2.49589041]
 [-3.27671233  1.49589041]
 [ 4.72328767  1.49589041]
 [14.72328767  1.49589041]
 [ 2.72328767 -0.50410959]
 [ 0.72328767 -0.50410959]
 [ 0.72328767 -0.50410959]
 [ 5.72328767 -1.50410959]
 [-1.27671233 -0.50410959]
 [ 1.72328767 -1.50410959]
 [ 6.72328767 -0.50410959]
 [-3.27671233 -1.50410959]
 [-5.27671233  0.49589041]
 [-3.27671233  2.49589041]
 [10.72328767 -0.50410959]
 [-2.27671233 -0.50410959]
 [ 2.72328767 -0.50410959]
 [-2.27671233  0.49589041]
 [-3.27671233  1.49589041]
 [-4.27671233 -0.50410959]
 [ 4.72328767 -0.50410959]
 [ 0.72328767 -0.50410959]
 [-2.27671233 -1.50410959]
 [ 7.72328767  0.49589041]
 [-0.27671233 -1.50410959]
 [-2.27671233  0.49589041]
 [-4.27671233  1.49589041]
 [ 0.72328767 -0.50410959]
 [-3.27671233  0.49589041]
 [-3.27671233 -0.50410959]
 [ 0.72328767 -1.50410959]
 [-2.27671233  1.49589041]
 [-6.27671233 -0.50410959]
 [-2.27671233 -1.50410959]
 [ 0.72328767  1.49589041]
 [ 4.72328767  1.49589041]
 [ 4.72328767  1.49589041]
 

In [5]:
residuals, beta = fit_var(centered_data, 3)
print(beta)

# changement de forme pour adapter et comparer a l'output de la fonction de fit statsmodels
beta_reshaped = beta.T.reshape(2, 3, 2)
print(beta_reshaped)

[[ 0.08755165  0.03879587]
 [ 0.44802598  0.09980406]
 [ 0.02517714  0.01597198]
 [ 0.18374761 -0.00692662]
 [ 0.01237941  0.00924795]
 [ 0.17983729 -0.04506648]]
[[[ 0.08755165  0.44802598]
  [ 0.02517714  0.18374761]
  [ 0.01237941  0.17983729]]

 [[ 0.03879587  0.09980406]
  [ 0.01597198 -0.00692662]
  [ 0.00924795 -0.04506648]]]


In [6]:
print(residuals)

[[ 1.30512792e+01  1.37807926e+00]
 [ 1.41803564e-01 -1.19196969e+00]
 [-2.62331345e-01 -7.60514498e-01]
 [ 4.58598692e-01 -5.97591725e-01]
 [ 6.01718046e+00 -1.54480536e+00]
 [-9.47792972e-01 -6.20484759e-01]
 [ 2.27490451e+00 -1.53550423e+00]
 [ 7.57070813e+00 -5.24663537e-01]
 [-3.30004130e+00 -1.76348738e+00]
 [-4.14343308e+00  5.78531780e-01]
 [-2.67059712e+00  2.60813532e+00]
 [ 1.02447381e+01 -5.75854349e-01]
 [-3.38967231e+00 -7.29046242e-01]
 [ 2.56282864e+00 -3.97450406e-01]
 [-2.18142671e+00  3.51535257e-01]
 [-3.15664779e+00  1.48607398e+00]
 [-4.63688111e+00 -5.34387434e-01]
 [ 5.07021178e+00 -1.81778642e-01]
 [ 5.07461434e-01 -4.74508305e-01]
 [-1.99687221e+00 -1.54395764e+00]
 [ 8.70310256e+00  6.52890415e-01]
 [-7.59669208e-01 -1.85669529e+00]
 [-1.56549513e+00  4.90090596e-01]
 [-4.20100017e+00  1.47965030e+00]
 [ 6.67646058e-01 -5.12914200e-01]
 [-3.34236932e+00  6.40213983e-01]
 [-3.35365763e+00 -3.34557339e-01]
 [ 1.30910680e+00 -1.30031145e+00]
 [-1.53964584e+00  1

In [7]:
# Assuming `data` and `residuals` are already defined
p = 3
omega, Theta, Phi = estimate_varma(data, p, residuals)
print("Omega:\n", omega)
print("Theta:\n", Theta)
print("Phi:\n", Phi)

Omega:
 [2.754102710500455, 1.09058888352562]
Theta:
 [[-0.4710846   0.091396  ]
 [ 0.13096128 -0.61153377]]
Phi:
 [[ 0.54983584 -0.09205653]
 [ 0.32750693  0.70744612]]


In [8]:
A = -Theta
print(f"A = {A}")
B = Phi+Theta
print(f"B = {B}")

A = [[ 0.4710846  -0.091396  ]
 [-0.13096128  0.61153377]]
B = [[ 0.07875124 -0.00066053]
 [ 0.45846821  0.09591235]]


In [21]:
#on cree un sous fichier pour y sauvegarder les replications
base_folder = "Real data"
os.makedirs(base_folder, exist_ok=True)
est = ([omega[0], A[0,0], A[0,1], B[0,0], B[0,1], omega[1], A[1,0], A[1,1], B[1,0], B[1,1]])

# Create DataFrame
estimstat = pd.DataFrame({
        'Parameter': [f'Parameter {i + 1}' for i in range(10)],
        'Mean': est,
        })

# Save DataFrame
estimstat_filename = f"estim_RD_MCO.csv"
estimstat_filepath = os.path.join(base_folder, estimstat_filename)
estimstat.to_csv(estimstat_filepath, index=False)
print(f"Saved statistics DataFrame to: {estimstat_filename}")

Saved statistics DataFrame to: estim_RD.csv
